#!/usr/bin/env bash

# Check if we've got a robot spawned yet
while (rosservice call /gazebo/get_model_state '{model_name: fetch}' | grep 'success: False') && (rosservice call /gazebo/get_model_state '{model_name: robot}' | grep 'success: False'); do sleep 1; done

spawn(){
  local name="$1"
  local uniqueid="$name$2"
  shift
  shift

  local x="$1"
  local y="$2"
  local z="$3"
  local yaw="$4"
  rosrun gazebo_ros spawn_model -database "$name" -sdf -model "$uniqueid" -x "$x" -y "$y" -z "$z" -Y "$yaw"
}

set_pose(){
  # Won't set yaw becasue quaternions...
  # Anything fancier than this and we'll have to spawn via Python a la
  # https://github.com/ros-simulation/gazebo_ros_pkgs/blob/kinetic-devel/gazebo_ros/scripts/spawn_model
  local name="$1"
  local uniqueid="$name$2"
  shift
  shift

  local x="$1"
  local y="$2"
  local z="$3"
  local yaw="$4"
  rosservice call /gazebo/set_model_state "model_state:
  model_name: \"$uniqueid\"
  pose:
    position:
      x: $x
      y: $y
      z: $z
    orientation:
      x: 0.0
      y: 0.0
      z: 0.0
      w: 0.0
  twist:
    linear:
      x: 0.0
      y: 0.0
      z: 0.0
    angular:
      x: 0.0
      y: 0.0
      z: 0.0
  reference_frame: ''
"
}

spawn_reset(){
  spawn "$@"
  set_pose "$@"
}

# Look through http://models.gazebosim.org/ for the default objects
spawn_reset coke_can 0       1.70 -5.10 0.45 1.57

# Make sure you've got the `standard_objects` repo built in the workspace.
# Use the .rosinstall file.

spawn_reset tuna 0        1.90 7.30 -2.96 0.03

spawn_reset jello 0         2.66 -3.00 0.01 1.57

spawn_reset "potted meat" 0 8.83 -1.93 0.01 0.70

spawn_reset "cracker" 0 6.55 -5.04 0.01 0.30

spawn_reset "beer" 0 4.82 -1.84 0.00 0.30

spawn_reset "tomato soup" 0 6.41 -0.89 0.00 0.30

spawn_reset "bleach" 0 8.58 -1.89 0.04 0.30

spawn_reset "pudding" 0 4.27 0.85 0.01 0.30

spawn_reset "pitcher" 0 4.78 1.31 0.01 0.30

spawn_reset "sugar" 0 5.14 1.14 0.01 0.30

spawn_reset "bowl" 0 -4.73 2.25 0.00 0.30

spawn_reset "cricket_ball" 0 -3.27 0.91 0.00 0.30

spawn_reset "plastic_cup" 0 -8.21 -3.76 0.01 0.30

spawn_reset "wood_cube_5cm" 0 -8.47 1.30 0.01 0.30

spawn_reset "wood_cube_10cm" 0 -7.71 1.64 0.01 0.30
